import pandas as pd

data = {
    "order_id": [1,2,3,4,5,6,7,8,9,10,11,12],
    "customer_id": ["C01","C02","C01","C03","C04","C02",
                    "C05","C01","C03","C06","C04","C05"],
    "product": ["Laptop","Mouse","Keyboard","Laptop","Monitor","Mouse",
                "Keyboard","Monitor","Mouse","Laptop","Keyboard","Laptop"],
    "category": ["Electronics","Accessories","Accessories","Electronics",
                 "Electronics","Accessories","Accessories","Electronics",
                 "Accessories","Electronics","Accessories","Electronics"],
    "quantity": [1,3,2,1,2,5,1,1,4,1,2,2],
    "price": [70000,800,1500,65000,20000,750,1200,18000,700,72000,1300,68000],
    "order_date": [
        "2026-01-05", "2026-01-07", "2026-01-10", "2026-01-15",
        "2026-02-02", "2026-02-10", "2026-02-15", "2026-02-20",
        "2026-03-01", "2026-03-05", "2026-03-10", "2026-03-15"
    ]
}

orders = pd.DataFrame(data)

#What is the total revenue?
#What is the total revenue generated by each product category?
#Which product generated the highest revenue?
#Find the top 3 customers based on total spending.
#Calculate the average order value.
#Find the number of unique customers.
#Find the customer who placed the most orders.
#Find the monthly revenue.
#Find the product with the highest total quantity sold.
#Sort the products by total revenue in descending order.

#Solutions

# Create revenue column
orders["revenue"] = orders["quantity"] * orders["price"]


# 1. Total revenue
total_revenue = orders["revenue"].sum()

print("Total revenue:", total_revenue)


# 2. Total revenue by product category
category_revenue = (
    orders.groupby("category")["revenue"]
    .sum()
)

print("\nRevenue by category:")
print(category_revenue)


# 3. Product with highest revenue
product_revenue = (
    orders.groupby("product")["revenue"]
    .sum()
)

highest_revenue_product = product_revenue.idxmax()

print("\nHighest revenue product:")
print(highest_revenue_product)


# 4. Top 3 customers based on total spending
customer_revenue = (
    orders.groupby("customer_id")["revenue"]
    .sum()
)

top_3_customers = customer_revenue.nlargest(3)

print("\nTop 3 customers:")
print(top_3_customers)


# 5. Average order value
average_order_value = orders["revenue"].mean()

print("\nAverage order value:")
print(average_order_value)


# 6. Number of unique customers
unique_customers = orders["customer_id"].nunique()

print("\nUnique customers:")
print(unique_customers)


# 7. Customer who placed the most orders
order_count = orders["customer_id"].value_counts()

most_orders_customer = order_count.idxmax()

print("\nCustomer with most orders:")
print(most_orders_customer)


# 8. Monthly revenue
orders["order_date"] = pd.to_datetime(orders["order_date"])

monthly_revenue = (
    orders.groupby(orders["order_date"].dt.to_period("M"))["revenue"]
    .sum()
)

print("\nMonthly revenue:")
print(monthly_revenue)


# 9. Product with highest total quantity sold
product_quantity = (
    orders.groupby("product")["quantity"]
    .sum()
)

highest_quantity_product = product_quantity.idxmax()

print("\nProduct with highest quantity sold:")
print(highest_quantity_product)


# 10. Products sorted by total revenue descending
sorted_products = (
    product_revenue
    .sort_values(ascending=False)
)

print("\nProducts sorted by revenue:")
print(sorted_products)